apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: db-api-exporter
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: db-api-exporter
  namespaceSelector:
    matchNames:
    - monitoring
  endpoints:
  - port: metrics
    interval: 15s
